version: "3.8"

services:
  db:
    image: postgres:16.1-bullseye
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: events
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_PORT: 5432
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  api: 
    build:
      dockerfile: ./Dockerfile
    restart: on-failure
    ports:
      - 80:80
    depends_on:
      - db

volumes:
  pg_data:
  stan_data: